version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./backend:/var/www/html/backend
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
